<?php echo $this->getChildHtml('PaketId_Shipping');?>

<?php $order = $this->getOrder(); ?>
<?php $shippings = Mage::getModel('paketid_shipping/result')->getCollection()->addOrderFilter($order); ?>

<!--
<?php if(count($shippings)):?>
<?php foreach($shippings as $shipping): ?>
<?php echo $this->__('Booking ID') ?>
<?php echo $shipping->getBookingID() ?>
<?php endforeach; ?>
<?php endif; ?>
-->